package api

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/gin-contrib/sessions"
	"github.com/gin-contrib/sessions/cookie"
	"github.com/gin-gonic/gin"

	"shellyadmin/internal/db"
	"shellyadmin/internal/services"
)

// loginTestSetup wires a minimal router slice mirroring the production
// auth chain so we can exercise the Login handler end-to-end (session
// middleware → handler → response) without dragging in the whole API.
func loginTestSetup(t *testing.T) (*gin.Engine, *Handler) {
	t.Helper()
	gin.SetMode(gin.TestMode)
	ensureSecretboxKey(t)

	dataDir := t.TempDir()
	database, err := db.Open(dataDir)
	if err != nil {
		t.Fatalf("db.Open() error = %v", err)
	}
	t.Cleanup(func() { _ = database.Close() })

	// PHC for the password "correct-horse" — fixed for deterministic tests.
	// Generated by services.HashPassword once; embedding it avoids a 90 ms
	// argon2 derivation per test case.
	hash, err := services.HashPassword("correct-horse")
	if err != nil {
		t.Fatalf("HashPassword error = %v", err)
	}

	cfg := Config{
		User:     "admin",
		PassHash: hash,
		Secret:   "test-secret",
		DataDir:  dataDir,
	}
	h := NewHandler(database, cfg)

	r := gin.New()
	store := cookie.NewStore([]byte(cfg.Secret))
	r.Use(sessions.Sessions("shellyadmin", store))
	r.POST("/api/login", h.Login)
	return r, h
}

func postLogin(t *testing.T, r *gin.Engine, username, password string) *httptest.ResponseRecorder {
	t.Helper()
	body, _ := json.Marshal(map[string]string{"username": username, "password": password})
	req := httptest.NewRequest("POST", "/api/login", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	r.ServeHTTP(rec, req)
	return rec
}

// TestLoginSucceedsWithRightCredentials is the baseline — locks in that
// the Q11 timing-oracle refactor and the Q20 lockout addition did not
// break the success path.
func TestLoginSucceedsWithRightCredentials(t *testing.T) {
	r, _ := loginTestSetup(t)
	rec := postLogin(t, r, "admin", "correct-horse")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200, body=%s", rec.Code, rec.Body.String())
	}
}

// TestLoginRejectsWrongPassword ensures verifyAdminPassword runs and
// rejects an incorrect password under the new always-run argon2 path.
func TestLoginRejectsWrongPassword(t *testing.T) {
	r, _ := loginTestSetup(t)
	rec := postLogin(t, r, "admin", "wrong")
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("status = %d, want 401, body=%s", rec.Code, rec.Body.String())
	}
}

// TestLoginRejectsWrongUsername guards Q11: the response must be 401 on
// an unknown username (not 200, not 423, and not a different status that
// would indirectly leak which usernames exist).
func TestLoginRejectsWrongUsername(t *testing.T) {
	r, _ := loginTestSetup(t)
	rec := postLogin(t, r, "nobody", "anything")
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("status = %d, want 401, body=%s", rec.Code, rec.Body.String())
	}
}

// TestLoginLocksAccountAfterMaxFailures locks in Q20: after
// LoginMaxFailures wrong attempts in a row, the account is locked and
// subsequent attempts return 423 even with the correct password.
func TestLoginLocksAccountAfterMaxFailures(t *testing.T) {
	r, _ := loginTestSetup(t)

	for i := 0; i < services.LoginMaxFailures; i++ {
		rec := postLogin(t, r, "admin", "wrong")
		if rec.Code != http.StatusUnauthorized {
			t.Fatalf("attempt %d: status = %d, want 401", i+1, rec.Code)
		}
	}

	// One more attempt with the CORRECT password — should still be locked.
	rec := postLogin(t, r, "admin", "correct-horse")
	if rec.Code != http.StatusLocked {
		t.Fatalf("post-lock attempt: status = %d, want 423 (account locked), body=%s",
			rec.Code, rec.Body.String())
	}
	// Retry-After header is set so a polite client can back off.
	if rec.Header().Get("Retry-After") == "" {
		t.Fatalf("expected Retry-After header on 423 response")
	}
}

// TestLoginUnlocksAfterSuccessClearsCounter verifies the counter resets
// on a successful login so a partial-failure burst followed by a
// successful login doesn't leave a half-charged lockout grenade for
// later innocent typos.
func TestLoginUnlocksAfterSuccessClearsCounter(t *testing.T) {
	r, h := loginTestSetup(t)
	// 5 wrong tries (< LoginMaxFailures so no lock yet)
	for i := 0; i < 5; i++ {
		_ = postLogin(t, r, "admin", "wrong")
	}
	// Correct login
	rec := postLogin(t, r, "admin", "correct-horse")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", rec.Code)
	}
	// Counter cleared by the successful login above; IsAccountLocked must
	// now report unlocked even though we crossed several failures earlier.
	locked, _ := h.service.IsAccountLocked("admin")
	if locked {
		t.Fatalf("expected unlocked after successful login")
	}
}

// TestLoginTimingFlatAcrossUsernameMismatch validates Q11: the response
// time for a wrong-username attempt should be the same order as a
// wrong-password attempt (both must run argon2). We allow generous
// slack — the goal is to detect the previous order-of-magnitude gap
// (<5 ms vs >50 ms), not micro-benchmark argon2.
func TestLoginTimingFlatAcrossUsernameMismatch(t *testing.T) {
	r, _ := loginTestSetup(t)

	measure := func(user, pass string) time.Duration {
		start := time.Now()
		_ = postLogin(t, r, user, pass)
		return time.Since(start)
	}
	// Warm up — first argon2 invocation can be slower due to memory alloc.
	measure("admin", "wrong")

	wrongUser := measure("nobody", "wrong")
	wrongPass := measure("admin", "wrong")
	// argon2 dominates at ~80 ms; if either is < 20 ms we know we missed
	// the unconditional verify path. Pre-fix wrongUser was typically < 5 ms.
	if wrongUser < 20*time.Millisecond {
		t.Fatalf("wrong-username path returned in %v, expected ~argon2 latency (>20ms)", wrongUser)
	}
	if wrongPass < 20*time.Millisecond {
		t.Fatalf("wrong-password path returned in %v, expected ~argon2 latency (>20ms)", wrongPass)
	}
}
